version: "2"

services:
    nginx:
        image: nginx:stable-alpine
        container_name: LEMP_nginx
        ports:
            - "8080:80"
        volumes:
            - ./www:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - LEMP_NET

    php:
        image: php:7-fpm-alpine
        container_name: LEMP_php
        volumes:
            - ./www:/var/www/html
        networks:
            - LEMP_NET

    mariadb:
        image: mariadb:latest
        container_name: LEMP_mariadb
        volumes:
            - ./database:/var/lib/mysql:rw
        depends_on:
            - nginx
        environment:
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - LEMP_NET

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: LEMP_pma
        ports:
            - "8880:80"
        environment:
            PMA_HOST: "mariadb"
        depends_on:
            - mariadb
        networks:
            - LEMP_NET
networks:
    LEMP_NET:
